# config.yml
version: "3.0"

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: ResponseSelector
  - name: FallbackClassifier

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: RulePolicy