# config.yml
version: "3.0"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper
- name: ResponseSelector
- name: FallbackClassifier

policies:
- name: MemoizationPolicy
- name: TEDPolicy
- name: RulePolicy
# assistant_id: 20240819-165713-convex-artifact
assistant_id: 20240819-172212-horizontal-impulse
