version: '3.8'

services:
  rasa:
    build:
      context: .
      dockerfile: dockerfile.rasp
    network_mode: host
    volumes:
      - ./data:/./data
      - ./models:/./models
      - ./actions:/./actions
      - ./config.yml:/./config.yml
      - ./domain.yml:/./domain.yml
    # First time run this
    # command: rasa init --no-prompt 
    # To fine tune run thie
    # command: rasa train

  action_server:
    image: rasa/rasa-sdk:3.5.0
    volumes:
      - ./actions:/app/actions
    network_mode: host