# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir torch
RUN pip install --no-cache-dir onnx
RUN pip install --no-cache-dir onnx-tf
RUN pip install --no-cache-dir transformers
RUN pip install tensorflow==2.13.0
RUN pip install tensorflow-probability
RUN pip install onnxsim
RUN pip install onnx2tf
RUN pip install onnx_graphsurgeon && \
    pip install psutil && \
    pip install sng4onnx
# Copy the conversion script into the container
COPY . .

# Set up entrypoint to run the conversion script
CMD ["bash"]