version: '3.8'

services:
  model_converter:
    build:
      context: .  # The context is the current directory where the Dockerfile is located
      dockerfile: dockerfile.reduce 
    volumes:
      - pytorch_models:/app/pytorch_models  # Volume for the PyTorch models
      - onnx_models:/app/onnx_models        # Volume for the ONNX models
      - tflite_models:/app/tflite_models    # Volume for the TensorFlow Lite models
      - ./convert_model_for_rasp.py:/app/convert_model_for_rasp.py
    environment:
      - MODEL_DIR=/app/pytorch_models
      - ONNX_DIR=/app/onnx_models
      - TFLITE_DIR=/app/tflite_models
    command: ["python", "convert_model_for_rasp.py"]

volumes:
  pytorch_models:
  onnx_models:
  tflite_models: