# Dockerfile
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install dependencies for STT and TTS
RUN apt-get update && apt-get install -y \
    libasound2 \
    pulseaudio \
    espeak-ng

# Install NLTK
RUN pip install --no-cache-dir nltk

# Install TTS and STT libraries
RUN pip install vosk
RUN pip install pyttsx3

# Download NLTK VADER lexicon
RUN python -m nltk.downloader vader_lexicon

# Copy the sentiment analysis scripts into the container
COPY test_sentiment_analysis .
COPY json_files .
COPY sentiment_analysis.py .
# Define the command to run the sentiment analysis script
# CMD ["python", "compare_models.py"]