version: '3'

services:
  mic_led:
    build: .
    container_name: mic_led_container
    privileged: true  # Necessary to access GPIO pins
    devices:
      - /dev/mem:/dev/mem
    restart: unless-stopped
