# Use a base image with Python 3.9
FROM python:3.9-slim

# Install system dependencies and build tools
RUN apt-get update && apt-get install -y \
    python3-gpiozero \
    alsa-utils \
    libasound2-dev \
    espeak-ng \
    libportaudio2 \
    libportaudiocpp0 \
    build-essential \
    gcc \
    libffi-dev \
    libgfortran5 \
    wget \
    && apt-get clean

# Set the working directory inside the container
WORKDIR /app

# Install Python dependencies including vosk and pyinstaller
RUN pip install pyttsx3 
RUN pip install vosk
RUN pip install sounddevice
RUN pip install pyinstaller

# Copy the application code
COPY . /app

# Use PyInstaller to create a standalone executable
RUN pyinstaller --noconsole --onefile --collect-all vosk converse.py

# The application will be in the dist directory created by PyInstaller
CMD ["./dist/converse"]
