version: '3.8'

services:
  raspberry_chatbot:
    build: 
      context: .
      dockerfile: dockerfile.rasp
    container_name: raspberry_chatbot
    devices:
      - "/dev/snd:/dev/snd"  # Audio devices
      - "/dev/gpiomem:/dev/gpiomem"  # GPIO memory
    volumes:
      - ./converse.py:/app/converse.py
      - ./json_files:/app/json_files
    environment:
      - PULSE_SERVER=host.docker.internal
      - LD_LIBRARY_PATH=/usr/local/lib/python3.9/site-packages/vosk
    command: ["python", "converse.py"]
    privileged: true  # Required to access GPIO and audio hardware

volumes:
  json_files:
