version: '3.8'

services:
  raspberry_chatbot:
    build: .
    container_name: raspberry_chatbot
    devices:
      - "/dev/snd:/dev/snd"  # Audio devices
      - "/dev/gpiomem:/dev/gpiomem"  # GPIO memory
    volumes:
      - ./your_application:/app
    environment:
      - PULSE_SERVER=host.docker.internal
    command: ["python", "converse.py"]
    privileged: true  # Required to access GPIO and audio hardware
