# Use Debian as the base image
FROM debian:bullseye-slim

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-gpiozero \
    alsa-utils \
    libasound2-dev \
    libportaudio2 \
    libportaudiocpp0 \
    build-essential \
    libffi-dev \
    gcc \
    python3-dev \
    wget \
    curl \
    git \
    && apt-get clean



# Install Python dependencies with specific versions
RUN pip3 install --no-cache-dir vosk==0.3.42 \
    sounddevice==0.4.1 \
    gpiozero==1.6.2 \
    nltk==3.6.3

# Print out the location of site-packages to find where vosk is installed
RUN python3 -c "import site; print(site.getsitepackages())"

# Set the working directory inside the container
WORKDIR /app

# Download NLTK VADER lexicon
RUN python3 -m nltk.downloader vader_lexicon

# Set the LD_LIBRARY_PATH to include the directory where libvosk.so is located
ENV LD_LIBRARY_PATH=/usr/local/lib/python3.9/site-packages/vosk

# Copy the application code into the working directory
COPY . /app

# Attempt to set permissions if libvosk.so is found
RUN chmod 755 /usr/local/lib/python3.9/site-packages/vosk/libvosk.so || echo "libvosk.so not found, skipping chmod"


# Run ldconfig to update the linker cache
RUN ldconfig

# Verify that libvosk.so can be found and loaded
RUN ldconfig -p | grep libvosk.so

# Run the application
CMD ["python3", "converse.py"]
