version: '3'

services:
  mic_led:
    build:
      context: .
      dockerfile: dockerfile.rasp
    container_name: mic_led_container
    privileged: true  # Necessary to access GPIO pins
    command: ["python3", "mic_led.py"]
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - ./mic_led.py:/mic_led/mic.py  # Mount mic.py from the host system
    restart: unless-stopped
