version: '3'
services:
  chatbot:
    build: 
      context: .
      dockerfile: dockerfile.rasp
    privileged: true  # Necessary for GPIO access
    devices:
      - /dev/snd:/dev/snd  # Map sound devices
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev/mem:/dev/mem
      - ./mic_led.py:/app/mic_led.py
    environment:
      - PYTHONUNBUFFERED=1
